apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master-deployment
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: leader
        image: cgarcia3/spark-master
        ports:
        - containerPort: 7077