fun main() {
    val comunidades = mutableMapOf<String, List<String>>()
    comunidades["Andalucia"] = listOf("Almeria", "Cadiz", "Cordoba", "Granada", "Huelva", "Jaen", "Granada", "Malaga", "Sevilla")
    comunidades["Aragon"] = listOf("Hueca", "Teruel", "Zaragoza")
    comunidades["Asturias"] = listOf("Asturias")
    comunidades["Baleares"] = listOf("Baleares")
    comunidades["Canarias"] = listOf("Las Palmas", "Sanat Cruz de Tenerife")
    comunidades["Cantabria"] = listOf("Cantabria")
    comunidades["Castilla-La Mancha"] = listOf("Albacete", "Ciudad Real", "Cuenca", "Guadalajara", "Toledo")
    comunidades["Castilla y Leon"] = listOf("Avila", "Burgos", "Leon", "Palencia", "Salamanca", "Segovia", "Soria", "Valladolid", "Zamora")
    comunidades["Cataluña"] = listOf("Barcelona", "Gerona", "Lerida", "Tarragona")
    comunidades["Comunidad Valenciana"] = listOf("Alicante", "Castellon", "Valencia")
    comunidades["Extremadura"] = listOf("Badajoz", "Caceres")
    comunidades["Galicia"] = listOf("La Coruña", "Lugo", "Orense", "Pontevedra")
    comunidades["La Rioja"] = listOf("La Rioja")
    comunidades["Madrid"] = listOf("Madrid")
    comunidades["Murcia"] = listOf("Murcia")
    comunidades["Navarra"] = listOf("Navarra")
    comunidades["Pais Vasco"] = listOf("Alava", "Guipuzcoa", "Vizcaya")

    print("Choose a community: ")
    val num = readLine()?.toInt()

    when (num) {
        1 -> println("Andalucia:${comunidades.getValue("Andalucia")}")
        2 -> println("Aragon:${comunidades.getValue("Aragon")}")
        3 -> println("Asturias:${comunidades.getValue("Asturias")}")
        4 -> println("Baleares:${comunidades.getValue("Baleares")}")
        5 -> println("Canarias:${comunidades.getValue("Canarias")}")
        6 -> println("Cantabria:${comunidades.getValue("Cantabria")}")
        7 -> println("Castilla-La Mancha:${comunidades.getValue("Castilla-La Mancha")}")
        8 -> println("Castilla y Leon:${comunidades.getValue("Castilla y Leon")}")
        9 -> println("Cataluña:${comunidades.getValue("Cataluña")}")
        10 -> println("Comunidad Valencia:${comunidades.getValue("Comunidad Valenciana")}")
        11 -> println("Extremadura:${comunidades.getValue("Extremadura")}")
        12 -> println("Galicia:${comunidades.getValue("Galicia")}")
        13 -> println("La Rioja:${comunidades.getValue("La Rioja")}")
        14 -> println("Madrid:${comunidades.getValue("Madrid")}")
        15 -> println("Murcia:${comunidades.getValue("Murcia")}")
        16 -> println("Navarra:${comunidades.getValue("Navarra")}")
        17 -> println("Pais Vasco:${comunidades.getValue("Pais Vasco")}")
        else -> println("No hay mas de 17 comunidades autonomas")
    }
}