# Generated by Django 3.2.17 on 2023-05-04 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_alter_game_publicid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='publicId',
            field=models.IntegerField(default=376808, help_text='Unique public id for game'),
        ),
    ]
