# Generated by Django 3.2.17 on 2023-05-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_alter_game_publicid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='publicId',
            field=models.IntegerField(default=338210, help_text='Unique public id for game'),
        ),
    ]
